package network;

public enum CommandType {
    LOGIN,
    GET_TABLES,
    ORDER_FOOD,
    PAY_BILL,
    GET_MENU,
    GET_ORDER,
    MANAGE_MENU_ADD,
    MANAGE_MENU_UPDATE,
    MANAGE_MENU_DELETE,
    GET_EMPLOYEES,
    MANAGE_EMPLOYEE_ADD,
    MANAGE_EMPLOYEE_UPDATE,
    MANAGE_EMPLOYEE_DELETE,
    GET_INVOICES,
    CHANGE_PASSWORD,
    GENERATE_ID,
    MANAGE_TABLE_DELETE,
    MANAGE_TABLE_ADD,
    MANAGE_TABLE_UPDATE,
    GET_THONG_KE,
    LOGOUT
}
